// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddElement(arg1) {
  return window['go']['main']['App']['AddElement'](arg1);
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function SaveTable(arg1) {
  return window['go']['main']['App']['SaveTable'](arg1);
}
