// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddElement(arg1:string):Promise<main.Lesson>;

export function Init():Promise<Array<main.Lesson>>;

export function SaveTable(arg1:Array<any>):Promise<void>;
