// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddElement(arg1) {
  return window['go']['scripts']['App']['AddElement'](arg1);
}

export function InitTable() {
  return window['go']['scripts']['App']['InitTable']();
}

export function SaveTable(arg1) {
  return window['go']['scripts']['App']['SaveTable'](arg1);
}
