// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddElement(arg1:string):Promise<models.Lesson>;

export function InitTable():Promise<Array<models.Lesson>>;

export function SaveTable(arg1:Array<any>):Promise<Array<Error>>;
